"""
Analyst Engine for Project EXODUS.

Rigorously validates or destroys each hypothesis generated by the pipeline.
Takes a hypothesis paired with the relevant observational data, executes the
test method specified by the hypothesis, and produces a multi-dimensional
validation result that either advances the candidate to the Breakthrough Engine
or explains it away as astrophysical or instrumental.

The five validation scores
--------------------------
1. **detection_score** (0-1): Strength of the anomaly actually found in the
   data.  A high value means the signal is loud and clear.
2. **natural_explanation_score** (0-1): Probability that a known astrophysical
   process (variable star, debris disc, stellar contamination, etc.) fully
   explains the anomaly.
3. **instrumental_score** (0-1): Probability that the anomaly is an
   instrumental or data-processing artefact (bad pixel, persistence, RFI,
   systematic).
4. **statistical_significance**: p-value against the null hypothesis of pure
   noise.  Lower is more significant.
5. **reproducibility** (0-1): Does the signal appear in at least one
   independent dataset or observation epoch?

Classification logic
--------------------
    UNEXPLAINED        strong detection AND natural < 0.5 AND instrumental < 0.3
    CONFIRMED_NATURAL  natural explanation >= 0.5
    CONFIRMED_ARTIFACT instrumental score >= 0.5
    INCONCLUSIVE       everything else

Supported test methods (referenced by hypothesis objects):
    ir_excess_comparison       -- Compare IR excess between target and control
    anomaly_detection_lightcurve -- Look for anomalous dimming events
    radio_search_targeted      -- Search BL radio data for narrowband signals
    single_transit_ir_correlation -- Correlate single-transit events with IR
    temporal_differencing      -- Compare radio surveys across decades
"""

from __future__ import annotations

import sys
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Callable, Dict, List, Optional

import numpy as np
from scipy import stats as sp_stats

# ── Project imports ──────────────────────────────────────────────────
sys.path.insert(0, str(__import__("pathlib").Path(__file__).resolve().parent.parent.parent))

from src.utils import get_config, get_logger, save_result, PROJECT_ROOT

log = get_logger("engines.analyst")


# =====================================================================
#  Configuration
# =====================================================================

def _anomaly_sigma() -> float:
    """Return the detection threshold in sigma from config."""
    try:
        cfg = get_config()
        return float(cfg["search"]["anomaly_sigma"])
    except Exception:
        return 3.0


# =====================================================================
#  Enums and data classes
# =====================================================================

class ValidationStatus(Enum):
    """Possible outcomes of hypothesis validation."""
    CONFIRMED_NATURAL  = "CONFIRMED_NATURAL"
    CONFIRMED_ARTIFACT = "CONFIRMED_ARTIFACT"
    UNEXPLAINED        = "UNEXPLAINED"
    INCONCLUSIVE       = "INCONCLUSIVE"
    BOUNDARY           = "BOUNDARY"  # near threshold, retained for review


class AACSClass(Enum):
    """Anomalous Astrophysics Cataloging System (AACS) taxonomy.

    When a candidate is classified as CONFIRMED_NATURAL, it is further
    sub-classified into one of these categories.  Even 'natural' anomalies
    have scientific value and may be publishable.
    """
    CLASS_1_INTRINSIC = "INTRINSIC"    # HR outlier, eruptive variable, pulsation
    CLASS_2_EXTRINSIC = "EXTRINSIC"    # dust/disc, eclipsing binary, contamination
    CLASS_3_TRANSIENT = "TRANSIENT"    # nova, flare, high-energy transient
    CLASS_4_ARTIFACT  = "ARTIFACT"     # instrumental, systematic, processing bug
    UNCLASSIFIED      = "UNCLASSIFIED"


@dataclass
class ValidationResult:
    """Full result of validating a single hypothesis.

    Attributes
    ----------
    hypothesis_id : str
        Unique identifier of the hypothesis being tested.
    status : ValidationStatus
        Classification outcome.
    detection_score : float
        Strength of the anomaly found (0-1).
    natural_explanation_score : float
        Probability the anomaly is astrophysical (0-1).
    instrumental_score : float
        Probability the anomaly is an artefact (0-1).
    statistical_significance : float
        p-value against the null hypothesis.
    reproducibility : float
        Whether the anomaly appears in independent data (0-1).
    explanation : str
        Human-readable explanation of the classification decision.
    timestamp : str
        ISO-8601 timestamp of when the validation was performed.
    """

    hypothesis_id: str
    status: ValidationStatus
    detection_score: float
    natural_explanation_score: float
    instrumental_score: float
    statistical_significance: float
    reproducibility: float
    explanation: str
    aacs_class: Optional[str] = None
    fdr_significant: Optional[bool] = None
    timestamp: str = field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )

    def to_dict(self) -> dict:
        """Serialise to a plain dictionary (JSON-friendly)."""
        d = asdict(self)
        d["status"] = self.status.value
        return d

    def summary(self) -> str:
        """One-line human-readable summary."""
        return (
            f"[{self.status.value}] "
            f"det={self.detection_score:.3f} "
            f"nat={self.natural_explanation_score:.3f} "
            f"inst={self.instrumental_score:.3f} "
            f"p={self.statistical_significance:.2e} "
            f"repr={self.reproducibility:.3f} "
            f"| {self.explanation}"
        )


# =====================================================================
#  Analyst Engine
# =====================================================================

class AnalystEngine:
    """Validate or destroy hypotheses with rigorous statistical testing.

    Parameters
    ----------
    detection_threshold : float or None
        Minimum detection_score required for UNEXPLAINED status.  Defaults
        to ``1 / anomaly_sigma`` from the project config (i.e. sigma=3 ->
        threshold ~0.33), ensuring a reasonable bar for advancement.
    """

    # Mapping from hypothesis test-method names to internal validators.
    _METHOD_REGISTRY: Dict[str, str] = {
        "ir_excess_comparison":          "validate_ir_excess",
        "anomaly_detection_lightcurve":  "validate_lightcurve_anomaly",
        "radio_search_targeted":         "validate_radio_search",
        "single_transit_ir_correlation": "validate_transit_ir_correlation",
        "temporal_differencing":         "validate_temporal_differencing",
    }

    def __init__(self, detection_threshold: Optional[float] = None):
        sigma = _anomaly_sigma()
        self.detection_threshold = detection_threshold or (1.0 / sigma)
        log.info(
            "AnalystEngine initialised (detection_threshold=%.4f, anomaly_sigma=%.1f)",
            self.detection_threshold,
            sigma,
        )

    # ── Classification logic ─────────────────────────────────────────

    def classify(
        self,
        detection: float,
        natural: float,
        instrumental: float,
    ) -> ValidationStatus:
        """Apply the critical classification rules.

        Parameters
        ----------
        detection : float
            detection_score (0-1).
        natural : float
            natural_explanation_score (0-1).
        instrumental : float
            instrumental_score (0-1).

        Returns
        -------
        ValidationStatus
        """
        if (
            detection > self.detection_threshold
            and natural < 0.5
            and instrumental < 0.3
        ):
            return ValidationStatus.UNEXPLAINED
        elif natural >= 0.5:
            return ValidationStatus.CONFIRMED_NATURAL
        elif instrumental >= 0.5:
            return ValidationStatus.CONFIRMED_ARTIFACT
        else:
            return ValidationStatus.INCONCLUSIVE

    # ── Main entry point ─────────────────────────────────────────────

    def validate(
        self,
        hypothesis: Dict[str, Any],
        data: Dict[str, Any],
    ) -> ValidationResult:
        """Validate a hypothesis against the provided data.

        Parameters
        ----------
        hypothesis : dict
            Must contain at minimum:
                - ``hypothesis_id`` (str)
                - ``test_method`` (str): one of the registered method names
            May also contain ``test_params`` (dict) with method-specific
            configuration overrides.
        data : dict
            Observational data relevant to the hypothesis.  The required
            keys depend on the test method.

        Returns
        -------
        ValidationResult
        """
        hyp_id = hypothesis.get("hypothesis_id", "unknown")
        method_name = hypothesis.get("test_method", "")
        test_params = hypothesis.get("test_params", {})

        log.info(
            "Validating hypothesis '%s' using method '%s'",
            hyp_id, method_name,
        )

        validator_attr = self._METHOD_REGISTRY.get(method_name)
        if validator_attr is None:
            log.warning(
                "Unknown test method '%s' for hypothesis '%s'; "
                "returning INCONCLUSIVE",
                method_name, hyp_id,
            )
            return ValidationResult(
                hypothesis_id=hyp_id,
                status=ValidationStatus.INCONCLUSIVE,
                detection_score=0.0,
                natural_explanation_score=0.0,
                instrumental_score=0.0,
                statistical_significance=1.0,
                reproducibility=0.0,
                explanation=f"Unknown test method: {method_name}",
            )

        validator_fn: Callable = getattr(self, validator_attr)

        try:
            result = validator_fn(data, test_params=test_params)
        except Exception as exc:
            log.error(
                "Validation failed for hypothesis '%s': %s", hyp_id, exc,
                exc_info=True,
            )
            return ValidationResult(
                hypothesis_id=hyp_id,
                status=ValidationStatus.INCONCLUSIVE,
                detection_score=0.0,
                natural_explanation_score=0.0,
                instrumental_score=0.0,
                statistical_significance=1.0,
                reproducibility=0.0,
                explanation=f"Validation error: {exc}",
            )

        # Override hypothesis_id from the hypothesis dict
        result.hypothesis_id = hyp_id

        # AACS classification for natural explanations
        if result.status == ValidationStatus.CONFIRMED_NATURAL:
            result.aacs_class = self._classify_aacs(hypothesis, data, result).value
        elif result.status == ValidationStatus.CONFIRMED_ARTIFACT:
            result.aacs_class = AACSClass.CLASS_4_ARTIFACT.value

        log.info("Validation complete: %s", result.summary())

        # Persist the result
        try:
            save_result(f"analyst_{hyp_id}", result.to_dict())
        except Exception as exc:
            log.warning("Could not save result: %s", exc)

        return result

    # ── AACS sub-classification ───────────────────────────────────────

    def _classify_aacs(
        self,
        hypothesis: Dict[str, Any],
        data: Dict[str, Any],
        result: ValidationResult,
    ) -> AACSClass:
        """Sub-classify a CONFIRMED_NATURAL result into AACS taxonomy.

        Uses heuristics based on the test method and data properties to
        determine whether the natural explanation is intrinsic stellar
        variability, extrinsic (dust/companion), or a transient event.
        """
        method = hypothesis.get("test_method", "")
        explanation = result.explanation.lower()

        # Intrinsic: known variable star, HR diagram outlier, pulsation
        intrinsic_keywords = [
            "variable", "pulsation", "eruptive", "rr_lyrae",
            "cepheid", "mira", "periodicity", "asymmetry",
        ]
        if any(kw in explanation for kw in intrinsic_keywords):
            return AACSClass.CLASS_1_INTRINSIC

        if data.get("known_variable_type"):
            return AACSClass.CLASS_1_INTRINSIC

        # Extrinsic: debris disc, eclipsing binary, dust, contamination
        extrinsic_keywords = [
            "yso", "disc", "disk", "binary", "eclips",
            "dust", "contamination", "debris",
        ]
        if any(kw in explanation for kw in extrinsic_keywords):
            return AACSClass.CLASS_2_EXTRINSIC

        if data.get("known_yso_fraction", 0) > 0.3:
            return AACSClass.CLASS_2_EXTRINSIC

        # Transient: high-energy event, nova, flare
        transient_keywords = [
            "transient", "nova", "flare", "gamma", "burst",
            "neutrino", "gravitational",
        ]
        if any(kw in explanation for kw in transient_keywords):
            return AACSClass.CLASS_3_TRANSIENT

        # If IR excess is the test method and natural, likely dust
        if method == "ir_excess_comparison":
            return AACSClass.CLASS_2_EXTRINSIC

        # Default
        return AACSClass.UNCLASSIFIED

    # ── Batch validation with FDR ─────────────────────────────────────

    def validate_batch(
        self,
        hypotheses_and_data: List[Dict[str, Any]],
        fdr_alpha: float = 0.05,
    ) -> List[ValidationResult]:
        """Validate a batch of hypotheses and apply FDR correction.

        Parameters
        ----------
        hypotheses_and_data : list of dict
            Each dict must contain 'hypothesis' and 'data' keys.
        fdr_alpha : float
            False discovery rate threshold.

        Returns
        -------
        list of ValidationResult
            Results with ``fdr_significant`` field populated.
        """
        log.info("Batch validation: %d hypotheses", len(hypotheses_and_data))

        results = []
        for item in hypotheses_and_data:
            hyp = item["hypothesis"]
            data = item["data"]
            result = self.validate(hyp, data)
            results.append(result)

        # Apply FDR correction to statistical significance values
        p_values = [r.statistical_significance for r in results]

        try:
            from src.core.statistics import benjamini_hochberg
            rejected, q_values = benjamini_hochberg(p_values, alpha=fdr_alpha)
            for i, r in enumerate(results):
                r.fdr_significant = bool(rejected[i])
                # Downgrade UNEXPLAINED to BOUNDARY if not FDR-significant
                if r.status == ValidationStatus.UNEXPLAINED and not r.fdr_significant:
                    r.status = ValidationStatus.BOUNDARY
                    r.explanation += (
                        f" [Downgraded to BOUNDARY: not FDR-significant "
                        f"at alpha={fdr_alpha}]"
                    )
            n_fdr = int(sum(rejected))
            log.info(
                "FDR correction: %d/%d hypotheses FDR-significant at alpha=%.3f",
                n_fdr, len(results), fdr_alpha,
            )
        except ImportError:
            log.warning("Could not import statistics module for FDR correction")

        return results

    # ── Test method: IR excess comparison ────────────────────────────

    def validate_ir_excess(
        self,
        data: Dict[str, Any],
        test_params: Optional[Dict[str, Any]] = None,
    ) -> ValidationResult:
        """Compare IR excess between a target sample and a control sample.

        Expected data keys
        ------------------
        target_excess : list[float]
            IR excess values (sigma) for the target sample.
        control_excess : list[float]
            IR excess values (sigma) for the control / field sample.
        known_yso_fraction : float, optional
            Fraction of target sample cross-matched with known young stellar
            objects (YSOs).  High values indicate a natural (protoplanetary
            disc) explanation.  Default 0.0.
        quality_flags : list[float], optional
            Per-source photometric quality scores (0=bad, 1=good).
            If the mean quality is low, instrumental_score increases.
        independent_confirmation : bool, optional
            Whether the excess was confirmed in an independent IR survey.
        """
        test_params = test_params or {}
        sigma_threshold = _anomaly_sigma()

        target = np.asarray(data.get("target_excess", []), dtype=np.float64)
        control = np.asarray(data.get("control_excess", []), dtype=np.float64)
        known_yso = float(data.get("known_yso_fraction", 0.0))
        quality = data.get("quality_flags")
        independent = bool(data.get("independent_confirmation", False))

        if len(target) == 0 or len(control) == 0:
            return ValidationResult(
                hypothesis_id="",
                status=ValidationStatus.INCONCLUSIVE,
                detection_score=0.0,
                natural_explanation_score=0.0,
                instrumental_score=0.0,
                statistical_significance=1.0,
                reproducibility=0.0,
                explanation="Insufficient data for IR excess comparison.",
            )

        # ---- Detection score ----
        # Fraction of target sources exceeding the anomaly threshold
        frac_anomalous = float(np.mean(target > sigma_threshold))
        # Median excess of the anomalous targets, normalised to [0,1]
        anomalous_mask = target > sigma_threshold
        if np.any(anomalous_mask):
            median_excess = float(np.median(target[anomalous_mask]))
            # Map sigma to [0,1]: 3sigma -> ~0.5, 10sigma -> ~0.9
            excess_strength = float(1.0 - np.exp(-median_excess / (2.0 * sigma_threshold)))
        else:
            excess_strength = 0.0
        detection_score = float(np.clip(
            0.5 * frac_anomalous + 0.5 * excess_strength, 0.0, 1.0
        ))

        # ---- Statistical significance (two-sample test) ----
        if len(target) >= 3 and len(control) >= 3:
            stat, p_value = sp_stats.mannwhitneyu(
                target, control, alternative="greater"
            )
        elif len(target) >= 1 and len(control) >= 1:
            stat, p_value = sp_stats.ranksums(target, control)
            p_value = float(p_value) / 2.0  # one-sided
        else:
            p_value = 1.0
        p_value = float(np.clip(p_value, 0.0, 1.0))

        # ---- Natural explanation score ----
        # High if many targets are known YSOs or if the excess distribution
        # is consistent with known debris-disc populations.
        control_mean = float(np.mean(control))
        control_std = float(np.std(control)) if len(control) > 1 else 1.0
        # How much of the target excess is explainable by the control tail?
        target_mean = float(np.mean(target))
        z_offset = (target_mean - control_mean) / max(control_std, 1e-10)
        tail_probability = float(sp_stats.norm.sf(z_offset))

        natural_score = float(np.clip(
            0.5 * known_yso + 0.3 * tail_probability + 0.2 * (1.0 - detection_score),
            0.0, 1.0,
        ))

        # ---- Instrumental score ----
        instrumental = 0.0
        if quality is not None:
            q = np.asarray(quality, dtype=np.float64)
            mean_quality = float(np.mean(q))
            # Low quality -> high instrumental score
            instrumental = float(np.clip(1.0 - mean_quality, 0.0, 1.0))
        # If the control sample also shows excess, it is likely systematic
        control_excess_frac = float(np.mean(control > sigma_threshold))
        instrumental = float(np.clip(
            0.6 * instrumental + 0.4 * control_excess_frac, 0.0, 1.0
        ))

        # ---- Reproducibility ----
        reproducibility = 0.8 if independent else 0.2

        # ---- Classify ----
        status = self.classify(detection_score, natural_score, instrumental)

        explanation_parts = [
            f"{frac_anomalous*100:.1f}% of targets exceed {sigma_threshold:.1f}sigma",
            f"Mann-Whitney p={p_value:.2e}",
            f"YSO fraction={known_yso:.2f}",
        ]
        if independent:
            explanation_parts.append("confirmed in independent survey")

        return ValidationResult(
            hypothesis_id="",
            status=status,
            detection_score=detection_score,
            natural_explanation_score=natural_score,
            instrumental_score=instrumental,
            statistical_significance=p_value,
            reproducibility=reproducibility,
            explanation="; ".join(explanation_parts),
        )

    # ── Test method: light-curve anomaly detection ───────────────────

    def validate_lightcurve_anomaly(
        self,
        data: Dict[str, Any],
        test_params: Optional[Dict[str, Any]] = None,
    ) -> ValidationResult:
        """Validate anomalous dimming events in a light curve.

        Expected data keys
        ------------------
        time : list[float]
            Time stamps of the light curve.
        flux : list[float]
            Normalised flux values (baseline ~1.0).
        flux_err : list[float], optional
            Per-point flux uncertainties.
        known_variable_type : str or None
            If the star is a known variable (e.g. "eclipsing_binary",
            "RR_Lyrae"), the natural explanation score increases.
        n_sectors : int, optional
            Number of independent TESS/Kepler sectors or campaigns.
            More sectors increase reproducibility.
        """
        test_params = test_params or {}
        sigma_threshold = _anomaly_sigma()

        time = np.asarray(data.get("time", []), dtype=np.float64)
        flux = np.asarray(data.get("flux", []), dtype=np.float64)
        flux_err = data.get("flux_err")
        known_var = data.get("known_variable_type")
        n_sectors = int(data.get("n_sectors", 1))

        if len(time) < 20 or len(flux) < 20:
            return ValidationResult(
                hypothesis_id="",
                status=ValidationStatus.INCONCLUSIVE,
                detection_score=0.0,
                natural_explanation_score=0.0,
                instrumental_score=0.0,
                statistical_significance=1.0,
                reproducibility=0.0,
                explanation="Insufficient light curve data (need >= 20 points).",
            )

        # ---- Detect dips ----
        median_flux = float(np.median(flux))
        if flux_err is not None:
            flux_err = np.asarray(flux_err, dtype=np.float64)
            noise = float(np.median(flux_err))
        else:
            # Estimate noise from MAD of point-to-point differences,
            # which is robust to long-term trends and outliers.
            # For Gaussian noise, MAD of diff / sqrt(2) recovers sigma.
            if len(flux) > 2:
                diff_flux = np.diff(flux)
                mad_diff = float(np.median(np.abs(diff_flux - np.median(diff_flux))))
                noise = 1.4826 * mad_diff / np.sqrt(2.0) if mad_diff > 0 else float(np.std(flux))
            else:
                mad = float(np.median(np.abs(flux - median_flux)))
                noise = 1.4826 * mad if mad > 0 else float(np.std(flux))

        if noise <= 0:
            noise = 1e-6

        # Identify points that dip below the median by more than sigma * noise
        dip_threshold = median_flux - sigma_threshold * noise
        dip_mask = flux < dip_threshold
        n_dips = int(np.sum(dip_mask))
        frac_dipping = float(n_dips) / len(flux)

        # Deepest dip
        deepest_dip = float(median_flux - np.min(flux))
        dip_sigma = deepest_dip / noise if noise > 0 else 0.0

        # ---- Detection score ----
        # Based on the significance of the deepest dip and the fraction of
        # anomalous points
        dip_strength = float(1.0 - np.exp(-dip_sigma / (2.0 * sigma_threshold)))
        detection_score = float(np.clip(
            0.6 * dip_strength + 0.4 * min(frac_dipping * 20.0, 1.0),
            0.0, 1.0,
        ))

        # ---- Statistical significance ----
        # p-value from a one-sample test: is the minimum flux consistent with
        # Gaussian noise around the median?
        p_value = float(sp_stats.norm.sf(dip_sigma))
        p_value = float(np.clip(p_value, 1e-300, 1.0))

        # ---- Asymmetry analysis (megastructure signature) ----
        # Compute asymmetry of each dip: ratio of ingress to egress duration
        asymmetry_scores = []
        if n_dips > 0:
            # Find contiguous dip regions
            dip_diff = np.diff(dip_mask.astype(int))
            starts = np.where(dip_diff == 1)[0] + 1
            ends = np.where(dip_diff == -1)[0] + 1
            if dip_mask[0]:
                starts = np.concatenate([[0], starts])
            if dip_mask[-1]:
                ends = np.concatenate([ends, [len(flux)]])
            for s, e in zip(starts, ends):
                if e - s < 4:
                    continue
                seg = flux[s:e]
                mid = len(seg) // 2
                left_mean = float(np.mean(seg[:mid]))
                right_mean = float(np.mean(seg[mid:]))
                rng = max(float(np.ptp(seg)), 1e-10)
                asym = abs(left_mean - right_mean) / rng
                asymmetry_scores.append(asym)

        mean_asymmetry = float(np.mean(asymmetry_scores)) if asymmetry_scores else 0.0

        # ---- Natural explanation score ----
        natural_score = 0.0
        explanation_parts = []

        if known_var:
            natural_score = 0.7
            explanation_parts.append(f"known variable type: {known_var}")
        # Symmetric dips are more likely natural (planetary transits)
        if mean_asymmetry < 0.2:
            natural_score = max(natural_score, 0.4)
            explanation_parts.append(f"symmetric dips (asym={mean_asymmetry:.3f})")
        # Very periodic dips are more likely eclipsing binaries.
        # Only check periodicity if there are sustained multi-point dips,
        # not just isolated single-point glitches (which are instrumental).
        # Count how many dip events span >= 3 consecutive points.
        n_sustained_events = 0
        if n_dips > 3:
            dip_diff = np.diff(dip_mask.astype(int))
            evt_starts = np.where(dip_diff == 1)[0] + 1
            evt_ends = np.where(dip_diff == -1)[0] + 1
            if dip_mask[0]:
                evt_starts = np.concatenate([[0], evt_starts])
            if dip_mask[-1]:
                evt_ends = np.concatenate([evt_ends, [len(flux)]])
            for es, ee in zip(evt_starts, evt_ends):
                if ee - es >= 3:
                    n_sustained_events += 1

        if n_sustained_events >= 2:
            # Check periodicity by autocorrelation
            centered = flux - median_flux
            autocorr = np.correlate(centered, centered, mode="full")
            autocorr = autocorr[len(autocorr) // 2:]
            if len(autocorr) > 10:
                autocorr_norm = autocorr / (autocorr[0] + 1e-30)
                # Find the first significant peak after lag 0
                peaks = []
                for i in range(2, len(autocorr_norm) - 1):
                    if (autocorr_norm[i] > autocorr_norm[i-1] and
                            autocorr_norm[i] > autocorr_norm[i+1] and
                            autocorr_norm[i] > 0.3):
                        peaks.append(i)
                        break
                if peaks:
                    natural_score = max(natural_score, 0.5)
                    explanation_parts.append("strong periodicity detected")

        natural_score = float(np.clip(natural_score, 0.0, 1.0))

        # ---- Instrumental score ----
        # Check for sudden jumps that suggest systematic offsets.
        # Instrumental artefacts produce isolated, extremely sharp
        # discontinuities that far exceed astrophysical variability.
        flux_diff = np.diff(flux)
        jump_sigma = np.abs(flux_diff) / noise
        n_jumps = int(np.sum(jump_sigma > 5.0 * sigma_threshold))
        # Both the fraction AND absolute count of extreme jumps matter.
        jump_fraction = float(n_jumps) / max(len(flux_diff), 1)
        # Even a handful of >15sigma jumps in an otherwise quiet light
        # curve strongly suggests instrumental origin.
        jump_count_score = float(np.clip(n_jumps / 5.0, 0.0, 1.0))
        # Sharpness: ratio of max single-step change to overall std.
        # Astrophysical dips are gradual; artefacts are sudden.
        flux_std = float(np.std(flux))
        max_jump = float(np.max(np.abs(flux_diff))) if len(flux_diff) > 0 else 0.0
        sharpness = max_jump / max(flux_std, 1e-10)
        sharpness_score = float(np.clip((sharpness - 3.0) / 10.0, 0.0, 1.0))

        instrumental = float(np.clip(
            0.3 * jump_fraction * 20.0 + 0.3 * jump_count_score + 0.4 * sharpness_score,
            0.0, 0.8,
        ))

        # If flux has a long-term trend (slope), may be instrumental
        if len(time) > 10:
            coeffs = np.polyfit(time, flux, 1)
            trend_strength = abs(coeffs[0]) * (time[-1] - time[0]) / noise
            if trend_strength > sigma_threshold:
                instrumental = max(instrumental, 0.5)
                explanation_parts.append(f"long-term trend detected ({trend_strength:.1f}sigma)")

        instrumental = float(np.clip(instrumental, 0.0, 1.0))

        # ---- Reproducibility ----
        # More sectors = higher reproducibility
        reproducibility = float(np.clip(1.0 - np.exp(-n_sectors / 2.0), 0.0, 1.0))

        # ---- Classify ----
        status = self.classify(detection_score, natural_score, instrumental)

        explanation_parts.insert(0, f"deepest dip={dip_sigma:.1f}sigma")
        explanation_parts.insert(1, f"{n_dips} dipping points")
        if mean_asymmetry > 0.3:
            explanation_parts.append(f"asymmetric dips (asym={mean_asymmetry:.3f})")

        return ValidationResult(
            hypothesis_id="",
            status=status,
            detection_score=detection_score,
            natural_explanation_score=natural_score,
            instrumental_score=instrumental,
            statistical_significance=p_value,
            reproducibility=reproducibility,
            explanation="; ".join(explanation_parts),
        )

    # ── Test method: targeted radio search ───────────────────────────

    def validate_radio_search(
        self,
        data: Dict[str, Any],
        test_params: Optional[Dict[str, Any]] = None,
    ) -> ValidationResult:
        """Validate a narrowband radio signal detection.

        Expected data keys
        ------------------
        candidates : list[dict]
            Each candidate dict should have: ``snr``, ``drift_rate_hz_per_s``,
            ``is_rfi`` (bool), ``frequency_hz``.
        noise_floor : float
            Estimated noise floor of the observation.
        n_observations : int, optional
            Number of independent ON-source observations.  Signal must
            appear in ON and not in OFF for high reproducibility.
        on_off_ratio : float, optional
            Ratio of signal strength in ON-source vs OFF-source pointings.
            Values >> 1 indicate a real sky-localised signal.
        """
        test_params = test_params or {}
        sigma_threshold = _anomaly_sigma()

        candidates = data.get("candidates", [])
        noise_floor = float(data.get("noise_floor", 1.0))
        n_obs = int(data.get("n_observations", 1))
        on_off = float(data.get("on_off_ratio", 1.0))

        if not candidates:
            return ValidationResult(
                hypothesis_id="",
                status=ValidationStatus.INCONCLUSIVE,
                detection_score=0.0,
                natural_explanation_score=0.1,
                instrumental_score=0.0,
                statistical_significance=1.0,
                reproducibility=0.0,
                explanation="No radio signal candidates found.",
            )

        # Filter non-RFI candidates
        non_rfi = [c for c in candidates if not c.get("is_rfi", True)]
        all_snrs = np.array([c.get("snr", 0.0) for c in candidates])
        clean_snrs = np.array([c.get("snr", 0.0) for c in non_rfi]) if non_rfi else np.array([])

        # ---- Detection score ----
        if len(clean_snrs) > 0:
            best_snr = float(np.max(clean_snrs))
            # Map SNR to detection score: SNR=10 -> ~0.5, SNR=30 -> ~0.9
            detection_score = float(1.0 - np.exp(-best_snr / 20.0))
        else:
            best_snr = 0.0
            detection_score = 0.0

        # ---- Statistical significance ----
        # Under Gaussian noise, the probability of a peak at SNR = s
        # in N_trials independent channels is approximately:
        n_trials = max(int(data.get("n_channels", 1000)), 1)
        single_p = float(sp_stats.norm.sf(best_snr))
        p_value = float(np.clip(1.0 - (1.0 - single_p) ** n_trials, 1e-300, 1.0))

        # ---- Natural explanation score ----
        # Narrowband radio signals from astrophysical sources are rare;
        # masers and pulsars have distinctive signatures.
        # Check for non-zero drift rate (astrophysical sources are typically
        # at rest in the LSR, while a transmitter on a rotating/orbiting
        # body would show Doppler drift)
        natural_score = 0.1  # baseline: narrowband signals are rarely natural
        has_drift = False
        if non_rfi:
            drift_rates = [abs(c.get("drift_rate_hz_per_s", 0.0)) for c in non_rfi]
            max_drift = max(drift_rates) if drift_rates else 0.0
            if max_drift < 0.01:
                # Zero drift -> could be local interference or a maser
                natural_score = 0.4
            else:
                has_drift = True
                natural_score = 0.1  # drifting signals are less likely natural

        natural_score = float(np.clip(natural_score, 0.0, 1.0))

        # ---- Instrumental score ----
        # High if most candidates are flagged as RFI
        n_rfi = len(candidates) - len(non_rfi)
        rfi_fraction = float(n_rfi) / max(len(candidates), 1)
        # If the ON-OFF ratio is near 1, signal is likely RFI
        on_off_penalty = float(np.clip(1.0 / max(on_off, 0.1), 0.0, 1.0))
        instrumental = float(np.clip(
            0.4 * rfi_fraction + 0.4 * on_off_penalty + 0.2 * (1.0 - detection_score),
            0.0, 1.0,
        ))

        # ---- Reproducibility ----
        # Higher with more observations and strong ON-OFF contrast
        obs_factor = float(np.clip(1.0 - np.exp(-n_obs / 3.0), 0.0, 1.0))
        on_off_factor = float(np.clip((on_off - 1.0) / 10.0, 0.0, 1.0)) if on_off > 1.0 else 0.0
        reproducibility = float(np.clip(
            0.6 * obs_factor + 0.4 * on_off_factor, 0.0, 1.0
        ))

        # ---- Classify ----
        status = self.classify(detection_score, natural_score, instrumental)

        explanation_parts = [
            f"{len(non_rfi)} clean candidates (of {len(candidates)} total)",
            f"best SNR={best_snr:.1f}",
            f"RFI fraction={rfi_fraction:.2f}",
            f"ON/OFF ratio={on_off:.1f}",
        ]
        if has_drift:
            explanation_parts.append("Doppler drift detected")
        if n_obs > 1:
            explanation_parts.append(f"{n_obs} independent observations")

        return ValidationResult(
            hypothesis_id="",
            status=status,
            detection_score=detection_score,
            natural_explanation_score=natural_score,
            instrumental_score=instrumental,
            statistical_significance=p_value,
            reproducibility=reproducibility,
            explanation="; ".join(explanation_parts),
        )

    # ── Test method: single-transit / IR-excess correlation ──────────

    def validate_transit_ir_correlation(
        self,
        data: Dict[str, Any],
        test_params: Optional[Dict[str, Any]] = None,
    ) -> ValidationResult:
        """Correlate single-transit events with IR excess measurements.

        Expected data keys
        ------------------
        transit_depths : list[float]
            Depths of single-transit events (fractional flux drop).
        ir_excess_sigmas : list[float]
            IR excess significance (in sigma) for each corresponding source.
        control_ir : list[float]
            IR excess for a control sample of non-transiting stars.
        n_matches : int
            Number of sources with both transit and IR measurements.
        """
        test_params = test_params or {}
        sigma_threshold = _anomaly_sigma()

        depths = np.asarray(data.get("transit_depths", []), dtype=np.float64)
        ir_sigmas = np.asarray(data.get("ir_excess_sigmas", []), dtype=np.float64)
        control_ir = np.asarray(data.get("control_ir", []), dtype=np.float64)
        n_matches = int(data.get("n_matches", min(len(depths), len(ir_sigmas))))

        if n_matches < 3 or len(depths) < 3 or len(ir_sigmas) < 3:
            return ValidationResult(
                hypothesis_id="",
                status=ValidationStatus.INCONCLUSIVE,
                detection_score=0.0,
                natural_explanation_score=0.0,
                instrumental_score=0.0,
                statistical_significance=1.0,
                reproducibility=0.0,
                explanation="Insufficient matched sources for correlation analysis.",
            )

        # Trim to equal length
        n = min(len(depths), len(ir_sigmas))
        depths = depths[:n]
        ir_sigmas = ir_sigmas[:n]

        # ---- Correlation test ----
        corr_coeff, corr_p = sp_stats.spearmanr(depths, ir_sigmas)
        corr_coeff = float(corr_coeff)
        corr_p = float(corr_p)

        # ---- Detection score ----
        # Strong if there is a significant positive correlation
        # and the IR excess values are themselves large
        corr_strength = float(np.clip(max(corr_coeff, 0.0), 0.0, 1.0))
        ir_anomalous_frac = float(np.mean(ir_sigmas > sigma_threshold))
        detection_score = float(np.clip(
            0.5 * corr_strength + 0.5 * ir_anomalous_frac, 0.0, 1.0
        ))

        # ---- Statistical significance ----
        p_value = float(np.clip(corr_p, 1e-300, 1.0))

        # ---- Natural explanation score ----
        # If the control sample also shows elevated IR, the correlation
        # may be driven by a population-level effect (e.g. dusty stars)
        if len(control_ir) >= 3:
            control_frac = float(np.mean(control_ir > sigma_threshold))
        else:
            control_frac = 0.0
        natural_score = float(np.clip(
            0.5 * control_frac + 0.3 * (1.0 - corr_strength) + 0.2 * max(0, -corr_coeff),
            0.0, 1.0,
        ))

        # ---- Instrumental score ----
        # Cross-instrument correlation is less likely to be instrumental
        instrumental = float(np.clip(0.1, 0.0, 1.0))

        # ---- Reproducibility ----
        # More matched sources = more reproducible
        reproducibility = float(np.clip(1.0 - np.exp(-n_matches / 10.0), 0.0, 1.0))

        # ---- Classify ----
        status = self.classify(detection_score, natural_score, instrumental)

        explanation = (
            f"Spearman rho={corr_coeff:.3f} (p={corr_p:.2e}); "
            f"{ir_anomalous_frac*100:.1f}% IR-anomalous; "
            f"control IR-anomalous={control_frac*100:.1f}%; "
            f"n_matched={n_matches}"
        )

        return ValidationResult(
            hypothesis_id="",
            status=status,
            detection_score=detection_score,
            natural_explanation_score=natural_score,
            instrumental_score=instrumental,
            statistical_significance=p_value,
            reproducibility=reproducibility,
            explanation=explanation,
        )

    # ── Test method: temporal differencing (radio surveys) ───────────

    def validate_temporal_differencing(
        self,
        data: Dict[str, Any],
        test_params: Optional[Dict[str, Any]] = None,
    ) -> ValidationResult:
        """Compare radio survey data across multiple epochs to find transients.

        Expected data keys
        ------------------
        epoch1_flux : list[float]
            Flux densities from the earlier epoch (e.g. NVSS, 1990s).
        epoch2_flux : list[float]
            Flux densities from the later epoch (e.g. VLASS, 2020s).
        epoch1_rms : float
            RMS noise of the earlier survey.
        epoch2_rms : float
            RMS noise of the later survey.
        n_sources : int
            Number of sources compared.
        source_type : str, optional
            If sources are known AGN / quasars, variability is expected.
        """
        test_params = test_params or {}
        sigma_threshold = _anomaly_sigma()

        flux1 = np.asarray(data.get("epoch1_flux", []), dtype=np.float64)
        flux2 = np.asarray(data.get("epoch2_flux", []), dtype=np.float64)
        rms1 = float(data.get("epoch1_rms", 0.001))
        rms2 = float(data.get("epoch2_rms", 0.001))
        n_sources = int(data.get("n_sources", min(len(flux1), len(flux2))))
        source_type = data.get("source_type")

        if n_sources < 2 or len(flux1) < 2 or len(flux2) < 2:
            return ValidationResult(
                hypothesis_id="",
                status=ValidationStatus.INCONCLUSIVE,
                detection_score=0.0,
                natural_explanation_score=0.0,
                instrumental_score=0.0,
                statistical_significance=1.0,
                reproducibility=0.0,
                explanation="Insufficient data for temporal differencing.",
            )

        n = min(len(flux1), len(flux2))
        flux1 = flux1[:n]
        flux2 = flux2[:n]

        # ---- Compute variability significance ----
        combined_rms = np.sqrt(rms1**2 + rms2**2)
        diff = flux2 - flux1
        diff_sigma = np.abs(diff) / max(combined_rms, 1e-10)

        # Sources with significant variability
        variable_mask = diff_sigma > sigma_threshold
        n_variable = int(np.sum(variable_mask))
        frac_variable = float(n_variable) / n

        # ---- Detection score ----
        if n_variable > 0:
            max_var_sigma = float(np.max(diff_sigma[variable_mask]))
            var_strength = float(1.0 - np.exp(-max_var_sigma / (2.0 * sigma_threshold)))
        else:
            max_var_sigma = 0.0
            var_strength = 0.0
        detection_score = float(np.clip(
            0.5 * var_strength + 0.5 * min(frac_variable * 10.0, 1.0),
            0.0, 1.0,
        ))

        # ---- Statistical significance ----
        # Binomial test: is the number of variable sources more than expected
        # from noise alone?
        expected_false_positive_rate = float(sp_stats.norm.sf(sigma_threshold))
        if n_variable > 0:
            p_value = float(sp_stats.binomtest(
                n_variable, n, expected_false_positive_rate, alternative="greater"
            ).pvalue)
        else:
            p_value = 1.0
        p_value = float(np.clip(p_value, 1e-300, 1.0))

        # ---- Natural explanation score ----
        natural_score = 0.2  # baseline
        if source_type and source_type.lower() in ("agn", "quasar", "blazar", "variable"):
            natural_score = 0.7
        # If variability is bidirectional (some brighter, some fainter),
        # it is more likely astrophysical scintillation
        if n_variable >= 2:
            var_diffs = diff[variable_mask]
            has_positive = bool(np.any(var_diffs > 0))
            has_negative = bool(np.any(var_diffs < 0))
            if has_positive and has_negative:
                natural_score = max(natural_score, 0.5)

        natural_score = float(np.clip(natural_score, 0.0, 1.0))

        # ---- Instrumental score ----
        # Systematic offset between surveys suggests calibration difference
        mean_offset = float(np.mean(diff))
        offset_sigma = abs(mean_offset) / max(combined_rms, 1e-10)
        instrumental = float(np.clip(offset_sigma / (5.0 * sigma_threshold), 0.0, 0.8))

        # ---- Reproducibility ----
        # Two-epoch comparison is inherently less reproducible;
        # only high if we have a third epoch or many variable sources
        reproducibility = float(np.clip(frac_variable * 2.0, 0.0, 0.6))

        # ---- Classify ----
        status = self.classify(detection_score, natural_score, instrumental)

        explanation = (
            f"{n_variable}/{n} sources variable at {sigma_threshold:.1f}sigma; "
            f"max variability={max_var_sigma:.1f}sigma; "
            f"mean offset={mean_offset:.3e}; "
            f"p={p_value:.2e}"
        )
        if source_type:
            explanation += f"; source_type={source_type}"

        return ValidationResult(
            hypothesis_id="",
            status=status,
            detection_score=detection_score,
            natural_explanation_score=natural_score,
            instrumental_score=instrumental,
            statistical_significance=p_value,
            reproducibility=reproducibility,
            explanation=explanation,
        )


# =====================================================================
#  CLI demo / self-test
# =====================================================================

if __name__ == "__main__":
    print()
    print("=" * 72)
    print("  Project EXODUS -- Analyst Engine Demo")
    print("=" * 72)

    engine = AnalystEngine()
    rng = np.random.default_rng(seed=42)

    # ------------------------------------------------------------------
    #  Test 1: Natural variable star (IR excess from debris disc)
    #  Expected: CONFIRMED_NATURAL
    # ------------------------------------------------------------------
    print("\n[1] Natural variable star with debris disc (IR excess)")
    print("-" * 60)

    # Simulate a population of stars where the "target" sample has mild
    # IR excess consistent with a debris disc, and most targets are
    # known YSOs.
    n_target = 50
    n_control = 200

    # Control stars: excess ~ N(0, 1)
    control_excess = rng.normal(0.0, 1.0, n_control)
    # Target stars: modest excess from debris discs ~ N(1.5, 1.0)
    # Not extreme enough to be truly anomalous
    target_excess = rng.normal(1.5, 1.0, n_target)

    hypothesis_natural = {
        "hypothesis_id": "HYP_NAT_001",
        "test_method": "ir_excess_comparison",
        "test_params": {},
    }
    data_natural = {
        "target_excess": target_excess.tolist(),
        "control_excess": control_excess.tolist(),
        "known_yso_fraction": 0.8,   # 80% are known young stellar objects
        "quality_flags": [0.95] * n_target,  # good photometry
        "independent_confirmation": False,
    }

    result1 = engine.validate(hypothesis_natural, data_natural)
    print(f"  Status:         {result1.status.value}")
    print(f"  Detection:      {result1.detection_score:.4f}")
    print(f"  Natural:        {result1.natural_explanation_score:.4f}")
    print(f"  Instrumental:   {result1.instrumental_score:.4f}")
    print(f"  Significance:   {result1.statistical_significance:.2e}")
    print(f"  Reproducibility:{result1.reproducibility:.4f}")
    print(f"  Explanation:    {result1.explanation}")
    expected1 = "CONFIRMED_NATURAL"
    actual1 = result1.status.value
    print(f"  Expected: {expected1}  Got: {actual1}  "
          f"{'PASS' if actual1 == expected1 else 'CHECK'}")

    # ------------------------------------------------------------------
    #  Test 2: Simulated injected signal (anomalous radio detection)
    #  Expected: UNEXPLAINED
    # ------------------------------------------------------------------
    print("\n[2] Simulated injected signal (narrowband radio)")
    print("-" * 60)

    # Simulate a strong, non-RFI, drifting signal with good ON-OFF
    hypothesis_signal = {
        "hypothesis_id": "HYP_SIGNAL_001",
        "test_method": "radio_search_targeted",
        "test_params": {},
    }
    data_signal = {
        "candidates": [
            {
                "snr": 35.0,
                "drift_rate_hz_per_s": 1.5,
                "is_rfi": False,
                "frequency_hz": 1420.405e6,
            },
            {
                "snr": 8.0,
                "drift_rate_hz_per_s": 0.0,
                "is_rfi": True,
                "frequency_hz": 1420.000e6,
            },
        ],
        "noise_floor": 0.8,
        "n_observations": 5,
        "on_off_ratio": 12.0,
        "n_channels": 2**20,
    }

    result2 = engine.validate(hypothesis_signal, data_signal)
    print(f"  Status:         {result2.status.value}")
    print(f"  Detection:      {result2.detection_score:.4f}")
    print(f"  Natural:        {result2.natural_explanation_score:.4f}")
    print(f"  Instrumental:   {result2.instrumental_score:.4f}")
    print(f"  Significance:   {result2.statistical_significance:.2e}")
    print(f"  Reproducibility:{result2.reproducibility:.4f}")
    print(f"  Explanation:    {result2.explanation}")
    expected2 = "UNEXPLAINED"
    actual2 = result2.status.value
    print(f"  Expected: {expected2}  Got: {actual2}  "
          f"{'PASS' if actual2 == expected2 else 'CHECK'}")

    # ------------------------------------------------------------------
    #  Test 3: Instrumental artefact (bad photometry light curve)
    #  Expected: CONFIRMED_ARTIFACT
    # ------------------------------------------------------------------
    print("\n[3] Instrumental artefact (systematic light curve jumps)")
    print("-" * 60)

    n_pts = 2000
    time_lc = np.linspace(0, 100, n_pts)
    flux_lc = np.ones(n_pts) + rng.normal(0, 0.001, n_pts)
    # Inject sharp single-point glitches at IRREGULAR intervals
    # (instrumental artefacts: cosmic rays, detector resets, etc.)
    for glitch_idx in [137, 289, 501, 734, 812, 1055, 1301, 1488, 1777]:
        flux_lc[glitch_idx] -= 0.10  # sharp single-point glitch
    # Add a sudden baseline offset at the midpoint (detector thermal drift)
    flux_lc[1000:] -= 0.003

    hypothesis_artifact = {
        "hypothesis_id": "HYP_ART_001",
        "test_method": "anomaly_detection_lightcurve",
        "test_params": {},
    }
    data_artifact = {
        "time": time_lc.tolist(),
        "flux": flux_lc.tolist(),
        "known_variable_type": None,
        "n_sectors": 1,
    }

    result3 = engine.validate(hypothesis_artifact, data_artifact)
    print(f"  Status:         {result3.status.value}")
    print(f"  Detection:      {result3.detection_score:.4f}")
    print(f"  Natural:        {result3.natural_explanation_score:.4f}")
    print(f"  Instrumental:   {result3.instrumental_score:.4f}")
    print(f"  Significance:   {result3.statistical_significance:.2e}")
    print(f"  Reproducibility:{result3.reproducibility:.4f}")
    print(f"  Explanation:    {result3.explanation}")
    expected3 = "CONFIRMED_ARTIFACT"
    actual3 = result3.status.value
    print(f"  Expected: {expected3}  Got: {actual3}  "
          f"{'PASS' if actual3 == expected3 else 'CHECK'}")

    # ------------------------------------------------------------------
    #  Test 4: Transit-IR correlation (inconclusive)
    #  Expected: INCONCLUSIVE (weak correlation, few sources)
    # ------------------------------------------------------------------
    print("\n[4] Weak transit-IR correlation (inconclusive case)")
    print("-" * 60)

    hypothesis_corr = {
        "hypothesis_id": "HYP_CORR_001",
        "test_method": "single_transit_ir_correlation",
        "test_params": {},
    }
    data_corr = {
        "transit_depths": rng.uniform(0.001, 0.01, 8).tolist(),
        "ir_excess_sigmas": rng.normal(1.0, 1.0, 8).tolist(),
        "control_ir": rng.normal(0.5, 1.0, 50).tolist(),
        "n_matches": 8,
    }

    result4 = engine.validate(hypothesis_corr, data_corr)
    print(f"  Status:         {result4.status.value}")
    print(f"  Detection:      {result4.detection_score:.4f}")
    print(f"  Natural:        {result4.natural_explanation_score:.4f}")
    print(f"  Instrumental:   {result4.instrumental_score:.4f}")
    print(f"  Significance:   {result4.statistical_significance:.2e}")
    print(f"  Reproducibility:{result4.reproducibility:.4f}")
    print(f"  Explanation:    {result4.explanation}")
    print(f"  Got: {result4.status.value}")

    # ------------------------------------------------------------------
    #  Summary
    # ------------------------------------------------------------------
    print("\n" + "=" * 72)
    print("  Summary")
    print("=" * 72)
    results = [
        ("Natural variable star",  expected1, result1),
        ("Injected radio signal",  expected2, result2),
        ("Instrumental artefact",  expected3, result3),
        ("Weak correlation",       "INCONCLUSIVE", result4),
    ]
    for label, expected, r in results:
        match = r.status.value == expected
        tag = "PASS" if match else "CHECK"
        print(f"  [{tag}] {label:30s}  expected={expected:20s}  got={r.status.value}")

    print()
    print("=" * 72)
    print("  Analyst Engine demo complete.")
    print("=" * 72)
    print()
